### ISSUE TITLE
Cómo le hiciste para compilar el tema?

### ISSUE THREAD

**Issue by UjpanDG** [sadrach-cl/catppuccin-gtk#1]
Intenté modificar un poco el color del fondo pero a la hora de guardar y reiniciar el tema no cambia nada.

**Comment by sadrach-cl** [comment]
Exactamente eso pasa, se debe trabajar con la base del codigo de whitesur. En este repositorio solo subí las reléase. Puedes hacer fork del tema original o decirme que quieres modificar para verlo en la proxima update. 

Saludos.

**Comment by UjpanDG** [comment]
Bueno, es que el fondo me gustaria que sea un poco mas oscuro [ #15121C ] para que se vea mejor (o asi pienso yo).

Tambien si se pudiese cambiar el color de la seleccion, esa que esta ahorita de azul, pasarlo a un gris para que contraste bien con el color del texto [ #2D293 ].

Y si pudiese, que en los botones esas de seleccion (por ejemplo, donde dice ordenar por: nombre, etc.) que sea de color verde [ #B3E1A3 ]
![Screenshot_2021-12-24-02-43-55_1366x768](https://user-images.githubusercontent.com/75690908/147371811-a701d658-eb82-4bf3-8132-554ab0b36d89.png)
 
Creo que solo eso se me viene a la mente, igual te agradezco por compartir el tema, esta super genial.

**Comment by sadrach-cl** [comment]
El fondo es de ese color porque los demas Port como nvim, terminales, etc. Estan usando ese que si no me falla la memoria es el black 3. La decisión gue para mantener consistencia. El color de la selección estoy trabajando para generarlo en verde, amarillo, naranjo y rojo. Segun la paleta de Catppuccin. Y la tercera, de los selectores en verde, coincidimos. Pero creo qué sería mas factible para post fiestas. Mañana espero tener un poco de tiempo y agregar una actualización agregando el gtk2. Pero me falta trabajar un poco los asset de esa variante.

**Comment by UjpanDG** [comment]
Ahh, okey. Gracias Bro!

**Comment by sadrach-cl** [comment]
Por cierto, ya publique una actualización con algunas de tus sugerencias

**Comment by UjpanDG** [comment]
Gracias men!
